
# The URL the site will be built for
base_url = "https://arturaugusto.me"

compile_sass = true
title = "after-dark theme"
description = ""
generate_feed = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[extra]
author = "Vincent"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
after_dark_title = "My blog"